### Добавить страницу
###
POST http://localhost:9999/pages
Content-Type: application/json

{
  "name":"Article1",
  "pic":"http://www.url1.ru",
  "article":"text1text1text1"
}

### Добавить страницу
###
POST http://localhost:9999/pages
Content-Type: application/json

{
  "name":"Article2",
  "pic":"http://www.url2.ru",
  "article":"text2text2text2"
}

### Добавить страницу
###
POST http://localhost:9999/pages
Content-Type: application/json

{
  "name":"Article3",
  "pic":"http://www.url3.ru",
  "article":"text3text3text3"
}

### Несуществующий url
###
GET http://localhost:9999/fff

### Запрос всех страниц
###
GET http://localhost:9999/pages

### Запрос страницы с id
###
GET http://localhost:9999/pages/:3

### Обновление страницы по id
###
PUT http://localhost:9999/pages/:1
Content-Type: application/json

{
  "name":"Article4",
  "pic":"http://www.url4.ru",
  "article":"text4text4text4"
}

### Запрос страницы с несуществующим id
###
GET http://localhost:9999/pages/:60

### Обновление страницы с несуществующим id
###
PUT http://localhost:9999/pages/:10
Content-Type: application/json

{
  "name":"Article4",
  "pic":"http://www.url4.ru",
  "article":"text4text4text4"
}

### Удаление страницы по id
###
DELETE http://localhost:9999/pages/:2

### Удаление страницы c несуществующим id
###
DELETE http://localhost:9999/pages/:222

### Запрос всех страниц
###
GET http://localhost:9999/pages