
###
GET http://localhost:9999/ok

###
POST http://localhost:9999/pages
Content-Type: application/json

{
  "name":"Article1",
  "pic":"http://www.url1.ru",
  "article":"text1text1text1"
}

###
POST http://localhost:9999/pages
Content-Type: application/json

{
  "name":"Article2",
  "pic":"http://www.url2.ru",
  "article":"text2text2text2"
}

###
POST http://localhost:9999/pages
Content-Type: application/json

{
  "name":"Article3",
  "pic":"http://www.url3.ru",
  "article":"text3text3text3"
}
###
GET http://localhost:9999/fff

###
GET http://localhost:9999/pages

###
GET http://localhost:9999/pages/:3

###
PUT http://localhost:9999/pages/:1
Content-Type: application/json

{
  "name":"Article4",
  "pic":"http://www.url4.ru",
  "article":"text4text4text4"
}

###
GET http://localhost:9999/pages/:6

###
PUT http://localhost:9999/pages/:10
Content-Type: application/json

{
  "name":"Article4",
  "pic":"http://www.url4.ru",
  "article":"text4text4text4"
}